version: 2.1
orbs:
  buildpacks: jkutner/buildpacks@0.0.7
  ruby: circleci/ruby@0.2.1
jobs:
  build:
    machine: true
    steps:
      - buildpacks/install-pack:
          version: "0.7.0"
      - checkout
      - run:
          command: |
            rvm install 2.6.6
            rvm use ruby-2.6.6
            export PATH="/opt/circleci/.rvm/rubies/ruby-2.6.6/bin:$PATH"
            export GEM_HOME="/opt/circleci/.rvm/gems/ruby-2.6.6"
            export GEM_PATH="/opt/circleci/.rvm/gems/ruby-2.6.6"
            gem install bundler -v 2.1.0
            bundle install
            bundle exec rake hatchet:setup_ci
            rspec spec/cnb/

workflows:
  main:
    jobs:
      - build

